@startuml

class Vaccine {
String id
String name
int cost
getter()
setter()
}

class Branch {
String id
String name
Location location
getter()
setter()
}

class Allocation {
String id
int count
String branchId
String vaccineId
getter()
setter()
}

class Slots{
String id
String branchId
Date from
Date to
getter()
setter()
}

class Schedule{
String id
String email
String allocationId
String slotId
boolean isApplied
Date appliedOn
Payment paymentType
String BranchId
getter()
setter()
}

enum Location {
Delhi
Mumbai
Pune
}

enum Payment {
Cash
Credit
Fawry
}
@enduml